"""made payment type optional

Revision ID: 57b1c40b4f33
Revises: 7916bde9ff59
Create Date: 2026-01-28 14:39:07.780103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57b1c40b4f33'
down_revision: Union[str, Sequence[str], None] = '7916bde9ff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'payment_type',
               existing_type=postgresql.ENUM('TRANSFER', 'CASH', 'CARD', name='paymenttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'payment_type',
               existing_type=postgresql.ENUM('TRANSFER', 'CASH', 'CARD', name='paymenttype'),
               nullable=False)
    # ### end Alembic commands ###
