"""added size id to sale item

Revision ID: 7916bde9ff59
Revises: 
Create Date: 2026-01-28 10:48:22.294096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7916bde9ff59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('size_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sale_items', 'product_sizes', ['size_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'size_id')
    # ### end Alembic commands ###
