"""add credit_applied to sales

Revision ID: a5c5bc40e334
Revises: 57b1c40b4f33
Create Date: 2026-01-28 14:48:37.459758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c5bc40e334'
down_revision: Union[str, Sequence[str], None] = '57b1c40b4f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with a server default to populate existing rows
    op.add_column('sales', sa.Column('credit_applied', sa.Numeric(scale=2), nullable=False, server_default='0.00'))
    # Remove the server default after column is added (optional, keeps schema clean)
    op.alter_column('sales', 'credit_applied', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'credit_applied')
    # ### end Alembic commands ###
